import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      padding: 20,
      backgroundColor: '#F0F8F8', 
    },
    title: {
      fontSize: 26,
      fontWeight: 'bold',
      color: '#008080', 
      marginBottom: 20,
      textAlign: 'center',
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      marginBottom: 15,
      backgroundColor: '#FFFFFF',
      elevation: 2,
    },
    textAreaWrapper: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      borderWidth: 1,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      marginBottom: 15,
      backgroundColor: '#FFFFFF',
      elevation: 2,
    },
    inputIcon: {
      padding: 7,
    },
    input: {
      flex: 1,
      padding: 12,
      fontSize: 16,
      color: '#333333',
    },
    textArea: {
      flex: 1,
      padding: 12,
      fontSize: 16,
      color: '#333333',
      height: 120,
      textAlignVertical: 'top',
    },
    imagePicker: {
      backgroundColor: '#008080', 
      padding: 12,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 15,
      elevation: 2,
    },
    imagePickerText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '600',
      marginLeft: 8,
    },
    imageContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginBottom: 15,
      justifyContent: 'center',
    },
    image: {
      width: 80,
      height: 80,
      borderRadius: 8,
      margin: 5,
      borderWidth: 1,
      borderColor: '#E0E0E0',
    },
    placeholderText: {
      color: '#A9A9A9',
      fontSize: 14,
      fontStyle: 'italic',
      textAlign: 'center',
    },
    addButton: {
      backgroundColor: '#008080', 
      padding: 15,
      borderRadius: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 20,
      elevation: 2,
    },
    addButtonText: {
      color: '#FFFFFF',
      fontSize: 18,
      fontWeight: '600',
      marginLeft: 8,
    },
  });
  export default styles;